travis:
  secure:
    BINSTAR_TOKEN: KO766taEGgTNfaofYJkQAWShmAe0hdVyWycUP1iapE0tsxfId7fC6cCpBaGJpgM+qhGNphVHav3PFVWCKyrMaaDDVZep6zDbE0DbKrg8KN6wKIg6VwBMwKXwMdCikA308xGYLjWP6JEvMzRqHo+XWZg7nZHNmdAX9mq8syeUGXDgV9Bcu/lnAktnnjVu3gFBkIvMxHbBb6IkbpNoeO4IcoOGMWg5EevbBLhTMzhPgAN3FPthvQo808nzBDY4trKve2y2xyXW5EtzrAg1OdSmw+sG1noZAEPJdlyMe/jGE9cmFgkeI/jUkfbuDKrhx/BAbJqhskZS20Q2SLuNZCt9m1NQi18lpif1HGUzqBJkYU+qPh1FKzsuHVJswpaVnH5AvP7FepT9ADnMfcagCA8oLcUT9qGtprvsE0KC+qJ84Zr3HlJBjLtVfE4ifOUIMTIFStrqfBczecjRH96gV60RPbxwfOQG5xbG6SAtOeNpSde3igDeZgjg4nSqgCGsMRyB0wu2gn+VW9nx6jniet69st0fj8WuDQ7LcTH8yCxNWCoj+XVrWitbuOSs4xMextJrvVEHWhAPSMkgwrYhN2vKVb/Nb46HVDMDpMutBnAYC2d7StW1vPuKZXvq9+spHnuhqyKg+XYXBTffB0M85rr5rV85+f2e0KWntJXnkYSo+6U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
