travis:
  secure:
    BINSTAR_TOKEN: cV2Ezj6msMselZmh0lmYw0jsknJmCnhl/jOq9ToqIfJbvrA9BpoUHx+Sds2c8e/SHQHU8vqn9RXhWvCeMEqTWi/lZCXBsFGyBk22lHFujFkbzp+v9qlSbikngPKpiIhek3deqA+X2h1yZSpayPzKQ99FiY4/pOSUHZAY7elNOzqQ0dGr3XiOOU3O0v/IXpOAVzIBGdzTWFq42tb+JYWcxOka9dRwZLA6SGe9qSq+Hs8yRggJ7vhliivGh9APVfi3CCQFhoqyvkSRSDyI0MDExQ0ESmzGM5wXdcPf6uS2OlTOYHWBIKMztoeMfuQawzSIk7EMn3MG42e+0YZuu1W4VrZxcd/yTiGHbW+QvvgtHBqPx1nbz863zLCGvWTPrjYuFkldIlUh3NcN5Hn/ebVd+KzmPox6XLywsEU/U4I/K38BqAadGLngTSfWnWtyZk3ztkakzENKzjUAaBZkOirffItF4xFiSsAE9mbNxHcTVuEoc12C0WFBHYNbOiuvZZvS6v6kLpnP03vpE08oQ6BoKdAg8skqfcQSipVoKLp2QEvTMZi8ftC4kHVYTK1XP2KPqEWOEQlShcy6H0niqzl72k4tShPRcQIBQlRZY6t0yH299gYwae/L1UQ6ADmmWoSBlVmizzGFHLlV89Z4fOYGTppr32MkeYldH2bT3obP/30=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
