travis:
  secure:
    BINSTAR_TOKEN: dDnEeAinNacU5av/0FpNJRbSxNT4kyf/X03CjV83lY5dDPocUQRzkDV3qhFeRoedgrO956A1l23o3a0gEjlP0KItrJ0eTA3tOn5MTrQqJygXH+r1XMj5faRusBXQXo1ft1okH7bHFQgn/sSU37+cBJcFY/yCjwbvYdWmDTHORWogfceZICdUNmZhSvvETgn0VRxGA+S32Fgms10aowngLFdDgLqvKUIgIFD287P9xpCeLsdMdMrPAoXtaRoyNRXWkO3sOIs19ZPFo+hFXHeyDV1/nLBuuyqqxidxHCg8sG7JzlacHfdAmgzCuLI0XV9H9F+H9ql72WfgCdxPd8Bia29chhM4jjCa6hRUKY33s819PD8Ajbl6JVe7iLLu2S7qkaHTqpp20QRdsU+Zo9DFii18n3DP+o02gPiRRge3sAODQbMzXzPnILFCbGh8M4X2/x0W+MbN2aDT4Ffmxqo9bBAJa3oM1dQl25N7LjmHB+9K5ejOwLbypK/x61lJBCrX2+iC3b3vW1LzhGU7j0lUgdZZ6NPBR4jITvKaiPsHFNNC3QTYqfVVozYJf63U74ZygGnnw1AmaKx8kIZTvcpFh1Pw6PZgprBQo/VBetohSZVBfWHC9NrDvcvwxu43pbwOsvuujtsT8ctq/WdjpULYgtAknPZK0bAou+ei/jaduek=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
