travis:
  secure:
    BINSTAR_TOKEN: jSYWOj33/zzxjQXn9fHheOW9NozPgRHHGgRE2QexqSjDMJ5wV45jRNrX9p3mXgIH/w0QmPe+jbMBIQtz4BlxTfMrY4b++hDG1X5ISEMtWNoBvSAYHlTqCeGz+Pm4cH8rOcKLmUqz5MBSHPXnhgE+ais6pg0vxmt6iLKdHZwZa9YsDBioiaObObFR2n9iVHsjzjy4woxs5m5cqwKZdbzlAmxOo51NljN/RAOoXVnH9CRnXqw7gNWxEGTidjhe/zOtuSTP5imdw//hFb91Wl1sg9kkeXZvfi4wSCpMB0DK7cOMgiOubAB7F/nqQgnxQIsbMUP0mhbBjwjVgcErGyaj1LcSm/B60R/l2DWvCt8gDWolRNIu4sIRs3JpHOo+D//dLh3msAl9PW4PnU5yMrSrBpK8eu6aCpKGg/IUGqRIojhYIZ9WnNIgwExU21HaneA00cfeNLsNi4TAE7f61T1tINiwQHdgZT5p+Wrvhpgb93hTZgvT73e348Wds9vAYFuMfKkEW9rLqV/Ol+b+Ta1/TAi6Pd2dNW5ZXOoA7k+AmpoYXgmcZHtybdfdbwANCdEwn9tvThUI58hcf91UoHJ0RkWoad7cUeA/EKeNjosjZYamffxAugrKpUn4DEfoiV5I9btNZ9hhpjjTEZ1UW1kRAb6U6b7ZHtgS3BYgGghftvA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
